image: gradle:8.5-jdk17

before_script:
  - chmod +x ./gradlew

stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    path:
      - build/test-results/
      - build/reports/tests/
